% EEGLAB paths
eeglab_path = 'C:\Users\maghaeeaval\Documents\MATLAB\eeglab2021.1'; % path to EEGLAB folder
addpath(eeglab_path)
eeglab nogui

%% paths
eeg_files_loc = '/wynton/group/lee/CDAC_Arrest_EEG/UTW'; % path to EDF files 
eeglab_path = '/wynton/home/amorim/maghaeeaval/CDAC_Arrest_EEG_preprocessing_UTW/eeglab2021.1'; % EEGLAB folder path 
scalp_map = '/wynton/home/amorim/maghaeeaval/CDAC_Arrest_EEG_preprocessing_UTW/standard_1005.elc'; % available with EEGLAB nut also in eamorim_shared
standard_BESA = '/CDAC_Arrest_EEG_preprocessing_UTW/standard_BESA.mat'; % available with EEGLAB nut also in eamorim_shared
avg152t1 = '~/CDAC_Arrest_EEG_preprocessing_UTW/avg152t1.mat';
standard_elp = '~/CDAC_Arrest_EEG_preprocessing_UTW/standard-10-5-cap385.elp';

channel_list = {'C3','C4','Cz','CZ',...
    'EEG C3-Ref1','EEG C4-Ref1','EEG Cz-Ref1',...
    'F3', 'F4','F7','F8',  ...
    'EEG F3-Ref1','EEG F4-Ref1','EEG F7-Ref1', 'EEG F8-Ref1', ...
    'FP1','FP2','FZ','Fp1','Fz', 'fz','Fp2',...
    'EEG Fp1-Ref1','EEG Fp2-Ref1','EEG Fpz-Ref1', ...
    'P3','P4','Pz','PZ'...
    'EEG P3-Ref1', 'EEG P4-Ref1','EEG Pz-Ref1',...
    'T3', 'T5','T4', 'T6',...
    'EEG T3-Ref1','EEG T4-Ref1', 'EEG T5-Ref1','EEG T6-Ref1',...
    'O1','O2',...
    'EEG O1-Ref1','EEG O2-Ref1'};

dataset = EEG_preprocess_feature(eeg_files_loc,eeglab_path,scalp_map,standard_BESA,avg152t1,standard_elp,channel_list); 

